# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(789, 477)
        MainWindow.setStyleSheet("background-color: rgb(46, 52, 54);\n"
"color: rgb(243, 243, 243);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 801, 441))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab_3)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, -1, 781, 411))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textBrowser = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.acos = QtWidgets.QPushButton(self.tab)
        self.acos.setGeometry(QtCore.QRect(120, 140, 101, 41))
        self.acos.setStyleSheet("background-color: rgb(109, 123, 129);")
        self.acos.setObjectName("acos")
        self.sin_2 = QtWidgets.QPushButton(self.tab)
        self.sin_2.setGeometry(QtCore.QRect(10, 340, 101, 41))
        self.sin_2.setStyleSheet("background-color: rgb(109, 123, 129);")
        self.sin_2.setObjectName("sin_2")
        self.leftBR = QtWidgets.QPushButton(self.tab)
        self.leftBR.setGeometry(QtCore.QRect(450, 140, 101, 41))
        self.leftBR.setStyleSheet("background-color: rgb(109, 123, 129);")
        self.leftBR.setObjectName("leftBR")
        self.cos = QtWidgets.QPushButton(self.tab)
        self.cos.setGeometry(QtCore.QRect(120, 290, 101, 41))
        self.cos.setStyleSheet("background-color: rgb(109, 123, 129);")
        self.cos.setObjectName("cos")
        self.rightBR = QtWidgets.QPushButton(self.tab)
        self.rightBR.setGeometry(QtCore.QRect(560, 140, 101, 41))
        self.rightBR.setStyleSheet("background-color: rgb(109, 123, 129);")
        self.rightBR.setObjectName("rightBR")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(0, 70, 771, 51))
        font = QtGui.QFont()
        font.setFamily("MathJax_Math")
        font.setPointSize(17)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(46, 52, 54);\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.ln = QtWidgets.QPushButton(self.tab)
        self.ln.setGeometry(QtCore.QRect(230, 190, 101, 41))
        self.ln.setStyleSheet("background-color: rgb(109, 123, 129);")
        self.ln.setObjectName("ln")
        self.miltiply = QtWidgets.QPushButton(self.tab)
        self.miltiply.setGeometry(QtCore.QRect(670, 240, 101, 41))
        self.miltiply.setStyleSheet("background-color: rgb(109, 123, 129);")
        self.miltiply.setObjectName("miltiply")
        self.mod = QtWidgets.QPushButton(self.tab)
        self.mod.setGeometry(QtCore.QRect(340, 140, 101, 41))
        self.mod.setStyleSheet("background-color: rgb(109, 123, 129);")
        self.mod.setObjectName("mod")
        self.button9 = QtWidgets.QPushButton(self.tab)
        self.button9.setGeometry(QtCore.QRect(560, 190, 101, 41))
        self.button9.setObjectName("button9")
        self.result = QtWidgets.QPushButton(self.tab)
        self.result.setGeometry(QtCore.QRect(560, 340, 101, 41))
        self.result.setStyleSheet("\n"
"color: rgb(120, 174, 213);")
        self.result.setObjectName("result")
        self.e = QtWidgets.QPushButton(self.tab)
        self.e.setGeometry(QtCore.QRect(230, 140, 101, 41))
        self.e.setAutoFillBackground(False)
        self.e.setStyleSheet("background-color: rgb(109, 123, 129);")
        self.e.setObjectName("e")
        self.dub = QtWidgets.QPushButton(self.tab)
        self.dub.setGeometry(QtCore.QRect(450, 340, 101, 41))
        self.dub.setObjectName("dub")
        self.asin = QtWidgets.QPushButton(self.tab)
        self.asin.setGeometry(QtCore.QRect(120, 190, 101, 41))
        self.asin.setStyleSheet("background-color: rgb(109, 123, 129);")
        self.asin.setObjectName("asin")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.tab)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 140, 101, 141))
        font = QtGui.QFont()
        font.setFamily("MathJax_Math")
        font.setBold(True)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.plainTextEdit.setAutoFillBackground(True)
        self.plainTextEdit.setCenterOnScroll(False)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.divivsion = QtWidgets.QPushButton(self.tab)
        self.divivsion.setGeometry(QtCore.QRect(670, 190, 101, 41))
        self.divivsion.setStyleSheet("background-color: rgb(109, 123, 129);")
        self.divivsion.setObjectName("divivsion")
        self.drop = QtWidgets.QPushButton(self.tab)
        self.drop.setGeometry(QtCore.QRect(670, 140, 101, 41))
        self.drop.setStyleSheet("background-color: rgb(109, 123, 129);")
        self.drop.setObjectName("drop")
        self.button3 = QtWidgets.QPushButton(self.tab)
        self.button3.setGeometry(QtCore.QRect(560, 290, 101, 41))
        self.button3.setStyleSheet("")
        self.button3.setObjectName("button3")
        self.button6 = QtWidgets.QPushButton(self.tab)
        self.button6.setGeometry(QtCore.QRect(560, 240, 101, 41))
        self.button6.setObjectName("button6")
        self.zero = QtWidgets.QPushButton(self.tab)
        self.zero.setGeometry(QtCore.QRect(340, 340, 101, 41))
        self.zero.setObjectName("zero")
        self.sqrt = QtWidgets.QPushButton(self.tab)
        self.sqrt.setGeometry(QtCore.QRect(230, 290, 101, 41))
        self.sqrt.setStyleSheet("background-color: rgb(109, 123, 129);")
        self.sqrt.setObjectName("sqrt")
        self.button2 = QtWidgets.QPushButton(self.tab)
        self.button2.setGeometry(QtCore.QRect(450, 290, 101, 41))
        self.button2.setObjectName("button2")
        self.atg = QtWidgets.QPushButton(self.tab)
        self.atg.setGeometry(QtCore.QRect(10, 290, 101, 41))
        self.atg.setStyleSheet("background-color: rgb(109, 123, 129);")
        self.atg.setObjectName("atg")
        self.square = QtWidgets.QPushButton(self.tab)
        self.square.setGeometry(QtCore.QRect(230, 340, 101, 41))
        self.square.setStyleSheet("background-color: rgb(109, 123, 129);")
        self.square.setObjectName("square")
        self.button8 = QtWidgets.QPushButton(self.tab)
        self.button8.setGeometry(QtCore.QRect(450, 190, 101, 41))
        self.button8.setObjectName("button8")
        self.log = QtWidgets.QPushButton(self.tab)
        self.log.setGeometry(QtCore.QRect(230, 240, 101, 41))
        self.log.setStyleSheet("background-color: rgb(109, 123, 129);")
        self.log.setObjectName("log")
        self.button1 = QtWidgets.QPushButton(self.tab)
        self.button1.setGeometry(QtCore.QRect(340, 290, 101, 41))
        self.button1.setObjectName("button1")
        self.button5 = QtWidgets.QPushButton(self.tab)
        self.button5.setGeometry(QtCore.QRect(450, 240, 101, 41))
        self.button5.setObjectName("button5")
        self.tg = QtWidgets.QPushButton(self.tab)
        self.tg.setGeometry(QtCore.QRect(120, 340, 101, 41))
        self.tg.setStyleSheet("background-color: rgb(109, 123, 129);")
        self.tg.setObjectName("tg")
        self.plus = QtWidgets.QPushButton(self.tab)
        self.plus.setGeometry(QtCore.QRect(670, 340, 101, 41))
        self.plus.setStyleSheet("background-color: rgb(109, 123, 129);")
        self.plus.setObjectName("plus")
        self.minus = QtWidgets.QPushButton(self.tab)
        self.minus.setGeometry(QtCore.QRect(670, 290, 101, 41))
        self.minus.setStyleSheet("background-color: rgb(109, 123, 129);")
        self.minus.setObjectName("minus")
        self.button4 = QtWidgets.QPushButton(self.tab)
        self.button4.setGeometry(QtCore.QRect(340, 240, 101, 41))
        self.button4.setObjectName("button4")
        self.sin = QtWidgets.QPushButton(self.tab)
        self.sin.setGeometry(QtCore.QRect(120, 240, 101, 41))
        self.sin.setStyleSheet("background-color: rgb(109, 123, 129);")
        self.sin.setObjectName("sin")
        self.button7 = QtWidgets.QPushButton(self.tab)
        self.button7.setGeometry(QtCore.QRect(340, 190, 101, 41))
        self.button7.setObjectName("button7")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SmartCalc"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"</style></head><body style=\" font-family:\'Ubuntu Mono Italic\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Инструкция по работе с SmartCalc V.3:</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Калькулятор имеет 2 режима работы:</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1. Расчет алгебраических выражений.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2. Построение графика по алгебраическому выражению.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Инструкция"))
        self.acos.setText(_translate("MainWindow", "acos"))
        self.sin_2.setText(_translate("MainWindow", "X"))
        self.leftBR.setText(_translate("MainWindow", "("))
        self.cos.setText(_translate("MainWindow", "cos"))
        self.rightBR.setText(_translate("MainWindow", ")"))
        self.label.setText(_translate("MainWindow", "0"))
        self.ln.setText(_translate("MainWindow", "ln"))
        self.miltiply.setText(_translate("MainWindow", "*"))
        self.mod.setText(_translate("MainWindow", "mod"))
        self.button9.setText(_translate("MainWindow", "9"))
        self.result.setText(_translate("MainWindow", "="))
        self.e.setText(_translate("MainWindow", "e"))
        self.dub.setText(_translate("MainWindow", "."))
        self.asin.setText(_translate("MainWindow", "asin"))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "X Value"))
        self.divivsion.setText(_translate("MainWindow", "/"))
        self.drop.setText(_translate("MainWindow", "AC"))
        self.button3.setText(_translate("MainWindow", "3"))
        self.button6.setText(_translate("MainWindow", "6"))
        self.zero.setText(_translate("MainWindow", "0"))
        self.sqrt.setText(_translate("MainWindow", "sqrt"))
        self.button2.setText(_translate("MainWindow", "2"))
        self.atg.setText(_translate("MainWindow", "atg"))
        self.square.setText(_translate("MainWindow", "^"))
        self.button8.setText(_translate("MainWindow", "8"))
        self.log.setText(_translate("MainWindow", "log"))
        self.button1.setText(_translate("MainWindow", "1"))
        self.button5.setText(_translate("MainWindow", "5"))
        self.tg.setText(_translate("MainWindow", "tg"))
        self.plus.setText(_translate("MainWindow", "+"))
        self.minus.setText(_translate("MainWindow", "-"))
        self.button4.setText(_translate("MainWindow", "4"))
        self.sin.setText(_translate("MainWindow", "sin"))
        self.button7.setText(_translate("MainWindow", "7"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Calculator"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "f(x) = y"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

